Northwind.WebUI/Models/PagingInfo.cs
using System;

namespace Northwind.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPage
        {
            get { return (int) Math.Ceiling((decimal) TotalItems/ItemsPerPage); }
        }
    }
}

Northwind.WebUI/Models/ProductsListViewModel.cs
using System.Collections.Generic;
using Domain;

namespace Northwind.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Products> Products { get; set; }
        public PagingInfo PagingInfo { get; set; } 
        public string CurrentCategory { get; set; }
    }
}

Northwind.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Domain.Abstract;
using Domain.Concrete;
using Domain.Entities;

namespace Northwind.WebUI.Controllers
{
    public class CartController : Controller
    {
        IProductRepository _productRepository = new ProductRepository();

        public CartController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }
        public ActionResult AddToCart(Cart cart, int productId)
        {
            Products product = _productRepository.Products
                .FirstOrDefault(x => x.ProductID == productId);
            if (product != null)
                cart.AddItem(product, 1);
            return PartialView(cart);
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout(Cart cart)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry your cart is empty");
            }
            if (ModelState.IsValid)
            {
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View("CartIsEmpty");
            }
        }
    }
}

Northwind.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Domain.Abstract;

namespace Northwind.WebUI.Controllers
{
    public class NavController : Controller
    {
        private readonly ICategoryRepository _repository;

        public NavController(ICategoryRepository repository)
        {
            _repository = repository;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.Category = category;
            IEnumerable<string> categories = _repository.Categories.Where(x => x.CategoryName == "Confections" || x.CategoryName == "Beverages").Select(x => x.CategoryName).OrderBy(x => x);
            return PartialView(categories);
            //return "Hello from nav controller";
        }
    }
}

Northwind.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Domain.Abstract;
using Domain.Entities;
using Northwind.WebUI.Models;

namespace Northwind.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        public int pageSize = 15;

        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = _productRepository.Products
                    .Where(x => category == null || x.Categories.CategoryName == category)
                    .OrderBy(p => p.ProductName)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ? 
                        _productRepository.Products.Count() :
                        _productRepository.Products.Count(x => x.Categories.CategoryName == category)
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            var product = _productRepository.Products.FirstOrDefault(x=> x.ProductID == productId);
            return product != null ? File(product.Categories.Picture, "image / jpg") : null;
        }
    }
}

Northwind.WebUI/Views/Cart/AddToCart.cshtml
@model Domain.Entities.Cart

<div id="cartStateDet">
    <table width="90%" align="center">
        <thead>
        <tr>
            <td align="center">Quantity</td>
            <td align="left">Item</td>
            <td align="right">Price</td>
            <td align="right">Subtotal</td>
        </tr>
        </thead>
        <tbody>
        @foreach (var line in Model.Lines)
        {
            <tr>
                <td align="center">@line.Quantity</td>
                <td align="left">@line.Product.ProductName</td>
                <td align="right">@line.Product.UnitPrice.Value.ToString("c")</td>
                <td align="right">@((line.Quantity*line.Product.UnitPrice.Value).ToString("c"))</td>
                <td>
                    @*@using (Html.BeginForm("RemoveFromCart", "Cart"))
                            {
                                        @Html.Hidden("ProductId", line.Product.ProductId)
                                        @Html.HiddenFor(x => x.ReturnUrl)
                                        <input class="actionButtons" type="Submit" value="Remove" />
                                    }*@
                </td>
            </tr>
        }
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3" align="right">Total:</td>
            <td align="right">
                @Model.ComputeTotalValue().ToString("c")
            </td>
        </tr>
        </tfoot>
    </table>
    @*@using (Html.BeginForm("Checkout", "Cart"))
        {
            <input class="ui-button" type="button" value="Buy" style="float: left;"/>
        }*@
        <input class="ui-button" type="button" value="Buy" onclick="location.href='@Url.Action("Checkout", "Cart")'" />
        <input class="ui-button" type="button" value="Continue " onclick="CloseCartWindow()" />    
</div>

Northwind.WebUI/Views/Cart/CartIsEmpty.cshtml
@{
    ViewBag.Title = "CartIsEmpty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sorry!</h2>
Please try again, your cart is empty! 

Northwind.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "North Wind: order submitted";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thank you for choosing us!</h2>

Northwind.WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div id="cart">
    <span class="caption">
        <b>Your cart:</b>
        @Model.Lines.Sum(x => x.Quantity) item(s),
        @Model.ComputeTotalValue().ToString("c")
    </span>

    @*@Html.ActionLink("Check out", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, null)*@
</div>

Northwind.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Northwind.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Northwind.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

Northwind.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>
    
@foreach (var cat in Model)
{
    @Html.RouteLink(cat, new
        {
            controller = "Product",
            action = "List",
            category = cat,
            page = 1
        },
        new
        {
            @class = cat == ViewBag.Category ? "selected" : null
        })
}

Northwind.WebUI/Views/Product/List.cshtml
@model Northwind.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

    @*<ul class="products">
        @foreach (var p in Model.Products)
        {
            Html.RenderPartial("ProductSummary", p);
        }
    </ul>*@
<div class="products">
    @foreach (var p in Model.Products)
    {
        Html.RenderPartial("ProductSummary", p);
    }
</div>
<div id="cartState" title="Shopping cart" class="table-responsive"></div>


<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

Northwind.WebUI/Views/Product/ProductSummary.cshtml
@model Domain.Products

@*<li class="product-wrapper">
    <h3>@Model.ProductName</h3>
    @Model.QuantityPerUnit
    <h4>@Model.UnitPrice.Value.ToString("C")</h4>
</li>*@
<div class="product-wrapper">
    <div class="product-photo">
        <img src="@Url.Action("GetImage", "Product", new {Model.ProductID})" height="100" width="100"/>
    </div>
    <h3>@Model.ProductName</h3>
    @Model.QuantityPerUnit
    <h4>@Model.UnitPrice.Value.ToString("C")</h4>
    @using (Ajax.BeginForm("AddToCart", "Cart", new AjaxOptions {UpdateTargetId = "cartState"}))
    {
        @Html.HiddenFor(x => x.ProductID)
        <input type="submit" value="+Add to cart" onclick="ShowCart()"/>
    }
</div>

Northwind.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/css/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.12.4.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/myJS.js"></script>
</head>
<body>
    <div class="wrapper">
        <header>
            @*@{ Html.RenderAction("Summary", "Cart");}*@
            <div class="header-image">
                <img src="../images/Northwind.jpg" alt="Nort Wind"/>
            </div>
            <h1>North Wind</h1>
        </header>
        <div id="categories">
            @{Html.RenderAction("Menu", "Nav");}
        </div>
        <div id="content">
            @RenderBody()
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year – All rights reserved. North Wind</p>
        </footer>
    </div>
</body>
</html>